library(tidyverse)
library(janitor)
library(gganimate)
library(gapminder)

billion <- read.csv("billionaires.csv")


new_billion = data.frame(year = c(),
                         name = c())




for(i in 2002:2019){
  temp = data.frame(year = i,
                    name = unique(billion$name))
  new_billion = rbind(new_billion,temp)
}


result = merge.data.frame(new_billion,b,all.x = TRUE, by = c("year","name"))
result[is.na(result)]=0


gap <- result %>%
  group_by(year) %>% 
  mutate(rank = min_rank(-net_worth),
         net_worth_lbl = paste0(" ",net_worth)) %>%
  filter(rank <=10) %>%
  arrange(year,rank) %>% 
  ungroup()

p <- ggplot(gap, aes(rank, group = name, 
                     fill = as.factor(name), color = as.factor(name))) +
  geom_tile(aes(y = net_worth/2,
                height = net_worth,
                width = 0.9), alpha = 0.8, color = NA) +
  geom_text(aes(y = 0, label = paste(name, " ")), vjust = 0.2, hjust = 1) + #labels for x-axis
  geom_text(aes(y=net_worth,label = net_worth_lbl, hjust=0)) +  #labels for y-axis
  coord_flip(clip = "off", expand = FALSE) + # we are displaying a horizontal bar and so the x and y coordinates need to be flipped
  scale_y_continuous(labels = scales::comma) + #default mode for a ggplot animation
  scale_x_reverse() +
  guides(color = FALSE, fill = FALSE) +
  
  labs(title='{closest_state}', x = "", y = "Net Worth in billion USD", #Title below the animation
       caption = "Sources: Forbes | Plot generated by Talha Kapadia") +
  theme(plot.title = element_text(hjust = 0, size = 22),
        axis.ticks.y = element_blank(),  # These relate to the axes post-flip
        axis.text.y  = element_blank(),  # These relate to the axes post-flip
        plot.margin = margin(2,2,2,4, "cm")) +
  
  transition_states(year, transition_length = 4, state_length = 1) #relative length of transition, will be rematched depending on number of cycles


# Download gifski_renderer (if not present)
animate(p, 600, fps = 20, duration = 30, width = 800, height = 600, renderer = gifski_renderer("gganim.gif")) #frame rate and parameters like width and height are decided

